---
- name: List order id
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    src_json: "{{playbook_dir}}/../json_files/orders.json"
  tasks:
    - name: read the json file
      include_vars:
        file: "{{src_json}}"
        name: order_data
    - name: print the List
      ansible.builtin.debug:
         msg: "{{order_data.orders | map(attribute = 'order_id') | list | to_json}}"
